__author__ = "A.G."
__copyright__ = "Copyright 2025, A.G."
__email__ = "andrei.guliaev@scilifelab.uu.se"
__license__ = "GPL-3"


# Include pipeline specific rules
include: "rules/common.smk"


# 'All' rule, must be specified before any other modules are
# included, since they also contain 'All' rule
rule all:
    input:
        compile_output_file_list,


# Include modules
module references:
    snakefile:
        github(
            "hydra-genetics/references",
            path="workflow/Snakefile",
            branch="develop",
        )
    config:
        config

# targets (bed)
use rule cnvkit_create_targets from references

# anti-targets (bed)
use rule cnvkit_create_anti_targets from references

# creates PoN (cnn)
use rule cnvkit_build_normal_reference from references
