__author__ = "A.G."
__copyright__ = "Copyright 2025, A.G."
__email__ = "andrei.guliaev@scilifelab.uu.se"
__license__ = "GPL-3"

import typing
import pandas as pd


def get_units_column(units: pd.DataFrame, column: str) -> typing.List[str]:
    """
    extract a column from units.tsv
    Args:
        units: DataFrame generated by importing a file following schema definition
               found in workflow/schema/units.schema.yaml
        column: the name of the requested column
    Returns:
        List of strings representing the content of the requested column, or an
        empty list if the column does not exist, or if all values are missing/empty
    """
    if column not in units.columns:
        return []
    return list(set(units[column][units[column].notna()]))


def get_aligner_bam(wildcards, config: dict, type_override: typing.Optional[str] = None) -> str:
    """Return the path to the merged BAM file for the configured aligner."""
    return _get_aligner_path(wildcards, config, type_override, ".bam")


def get_aligner_bai(wildcards, config: dict, type_override: typing.Optional[str] = None) -> str:
    """Return the path to the BAM index file for the configured aligner."""
    return _get_aligner_path(wildcards, config, type_override, ".bam.bai")


def _get_aligner_path(wildcards, config: dict, type_override: typing.Optional[str], extension: str) -> str:
    aligner = config.get("aligner", "pbmm2")
    t = type_override if type_override is not None else wildcards.type
    return f"alignment/{aligner}_align/{wildcards.sample}_{t}{extension}"
