---
 files:
   - name: "cnvkit_pon"
     output: "results/cnvkit_build_normal_reference/cnvkit.PoN.cnn"
     input: "references/cnvkit_build_normal_reference/cnvkit.PoN.cnn"
   - name: "deepsomatic_pon"
     output: "results/bcftools_merge/normal_db.vcf.gz"
     input: "references/bcftools_merge/normal_db.vcf.gz"
   - name: "multiqc_html_report"
     output: "results/qc/multiqc/multiqc_design2.html"
     input: "qc/multiqc/multiqc_DNA.html"