name: Lint

# Controls when the action will run.
on:
   # Triggers the workflow on push or pull request events but only for the master and develop branch
  push:
    branches:
     - develop
     - main
  pull_request:
    branches:
     - develop
     - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  lint:
    name: Lint workflow
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: prefix-dev/setup-pixi@v0.8.1
        with:
          pixi-version: v0.39.0
          cache: true
      - name: Linting
        working-directory: .tests/integration
        run: |
          pixi run snakemake --lint -n -s ../../workflow/Snakefile --configfiles ../../config/config.yaml config/config.yaml
